# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
theme: tale

# Site settings
title: "회사원말고 프로그래머"
description: "진짜 프로그래머가 되고싶은 sewonkimm의 개발기록"
url: "https://sewonkimm.github.io"

# Google Analytics
google_analytics: UA—G-TJY9MJ7NPP

# Author
author:
  name: SeWon Kim
  email: swon962@gmail.com
  url: https://sewonkimm.github.io

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji #Uncomment this to allow emoji in your post

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

# Disqus (Set to your disqus id)
disqus: jekyll-tale

paginate: 5
paginate_path: "page:num"
highlighter: rouge

future: true
